7477.master
ivandudardb/ddev pull request #37
Opened 2024-02-26 07:02 UTC by ivandudardb

2024-02-26 07:22 UTC, HeorhiiBoliuk reviewed
Something with components files. You are adding to a component file a node data information from the site

2024-02-26 07:22 UTC, HeorhiiBoliuk commented on web/themes/custom/customtheme/components/01-atoms/advertisement/advertisement-wide.twig
All components using the template of block content.

2024-02-26 08:56 UTC, HeorhiiBoliuk requested changes

2024-02-26 08:56 UTC, HeorhiiBoliuk commented on config/default/block.block.customtheme_authorblock.yml
> +    pages: "<front>\r\n/user/*\r\n/category/*\r\n/node/162"
This string is look like you are showing this block by node id

2024-02-26 08:56 UTC, HeorhiiBoliuk commented on config/default/block.block.customtheme_page_title.yml
> +    pages: "/category/*\r\n/node/162"
This string looking like you are showing the view in the node using his id.

2024-02-26 08:56 UTC, HeorhiiBoliuk commented on config/default/block.block.customtheme_views_block__more_articles_block_1.yml
> +    pages: "/newspaper_pulses_pro\r\n/user/*\r\n/category/*\r\n/node/162"
The same like first and second comment

2024-02-26 08:56 UTC, HeorhiiBoliuk commented on config/default/block.block.customtheme_views_block__must_read_block_1.yml
> +    pages: "/user/*\r\n/category/*\r\n<front>\r\n/node/162"
The same

2024-02-26 08:56 UTC, HeorhiiBoliuk commented on web/themes/custom/customtheme/components/01-atoms/advertisement/advertisement-wide.twig
> +{{ view.field.field_dvertisement_photo.original_value }}
Dont use views data in a component

2024-02-26 08:56 UTC, HeorhiiBoliuk commented on web/themes/custom/customtheme/components/01-atoms/node-teaser-date/node-teaser-date.twig
> +  {{ author_name }} - {{ node.createdtime|format_date('custom', 'F j, Y') }}
Dont use views data in a component

2024-02-26 08:56 UTC, HeorhiiBoliuk commented on web/themes/custom/customtheme/components/01-atoms/node-teaser-image/node-teaser-image.twig
> +  {{ content.field_photo.0 }}
Dont use views data in a component

2024-02-26 08:56 UTC, HeorhiiBoliuk commented on web/themes/custom/customtheme/components/01-atoms/node-teaser-term/node-teaser-term.twig
> +  {{ content.field_category.0 }}
Dont use views data in a component

2024-02-26 08:56 UTC, HeorhiiBoliuk commented on web/themes/custom/customtheme/components/01-atoms/node-teaser-text/node-teaser-text.twig
> +  {{ node.field_teaser_text.value }}
Dont use views data in a component

2024-02-26 08:56 UTC, HeorhiiBoliuk commented on web/themes/custom/customtheme/components/01-atoms/title/title.twig
> +<a href="{{ node_url }}" class="node-link">{{ node_title }}</a>
Dont use views data in a component

2024-02-26 08:56 UTC, HeorhiiBoliuk commented on web/themes/custom/customtheme/components/02-molecules/news-teaser/news-teaser.twig
Dont use views data in a component

2024-02-26 12:32 UTC, HeorhiiBoliuk approved these changes
All issues is fixed

2024-02-27 11:52 UTC, lavrenchuk-dev approved these changes

2024-02-27 11:52 UTC, merged