7584.master
ivandudardb/ddev pull request #48
Opened 2024-03-04 12:49 UTC by ivandudardb

Added and utilized the AddToAny module.
Arranged blocks on the page using Layout Builder.
Revised the user block (made it using Views).

2024-03-04 13:03 UTC, HeorhiiBoliuk approved these changes
Looks good

2024-03-04 13:08 UTC, lavrenchuk-dev requested changes

2024-03-04 13:08 UTC, lavrenchuk-dev commented on web/themes/custom/customtheme/customtheme.theme
> +  // Модифікуємо значення #title для посилання.
ごめんなさい、ウクライナ語はわかりません

2024-03-06 06:47 UTC, ivandudardb commented on web/themes/custom/customtheme/customtheme.theme
> -}
These were my unsuccessful attempts to add a title to the pager

2024-03-06 07:30 UTC, lavrenchuk-dev commented
@ivandudardb Commit message should describe changes that were made in that commit.
"Requested changes" doesn't describe anything, maybe in the context of PR, but just naming it "removed useless hook" is already much more descriptive.

2024-03-06 07:30 UTC, merged