7761 - custom cache context added
ivandudardb/ddev pull request #66
Opened 2024-03-25 08:02 UTC by ivandudardb

created and used a custom cache context

2024-03-25 08:07 UTC, faust174 reviewed
LGTM

2024-03-26 07:11 UTC, lavrenchuk-dev requested changes

2024-03-26 07:11 UTC, lavrenchuk-dev commented on web/modules/custom/custom_weather/src/Cache/CustomWeatherContext.php
> + *
*

2024-03-26 07:11 UTC, lavrenchuk-dev commented on web/modules/custom/custom_weather/src/Cache/CustomWeatherContext.php
> +    return 'custom_cache_context:' . $city;
custom_comment_review

2024-03-26 07:11 UTC, lavrenchuk-dev commented on web/modules/custom/custom_weather/src/Cache/CustomWeatherContext.php
> +    protected Connection $connection,
is it used?

2024-03-26 07:11 UTC, lavrenchuk-dev commented on web/modules/custom/custom_weather/src/Cache/CustomWeatherContext.php
> +    protected AccountProxyInterface $accountProxy,
is it used?

2024-03-26 10:02 UTC, lavrenchuk-dev approved these changes

2024-03-26 10:02 UTC, merged