7743 - drush command and hook_post_update_hook for replace text forma…
ivandudardb/ddev pull request #67
Opened 2024-03-26 07:04 UTC by ivandudardb

…t created
Created a new text format called "limited HTML". 
Implemented the ability to replace the text format using the custom Drush command and HOOK_post_update_HOOK.

2024-03-26 07:39 UTC, KuzyaWkk commented on web/modules/custom/drush_update/src/Commands/CustomCommands.php
> +   */
The name doesn't make it clear what this team does

2024-03-26 07:44 UTC, KuzyaWkk commented on web/modules/custom/drush_update/src/Commands/CustomCommands.php
> +    $paragraph->get('field_regular_text')->format = $context;
You can load multiple entities at once to make this 10 times faster

2024-03-26 07:49 UTC, KuzyaWkk commented on web/modules/custom/batch_update/batch_update.post_update.php
> +  $limit = 50;
you could also avoid querying all of IDs
To make sure that this will not fault no matter of how much entities you have.

2024-03-26 07:50 UTC, KuzyaWkk requested changes
Fix the error above

2024-03-26 14:53 UTC, KuzyaWkk approved these changes
Looks good

2024-03-27 06:26 UTC, lavrenchuk-dev approved these changes

2024-03-27 06:26 UTC, merged