7766.master
ivandudardb/ddev pull request #69
Opened 2024-04-02 06:20 UTC by ivandudardb

2024-04-02 06:37 UTC, HeorhiiBoliuk requested changes

2024-04-02 06:37 UTC, HeorhiiBoliuk commented on web/modules/custom/color_button_ckeditor_plugin/color_button_ckeditor_plugin.ckeditor5.yml
> +      - <section class="simple-box">
this is looks weird

2024-04-02 06:40 UTC, HeorhiiBoliuk approved these changes

2024-04-03 09:17 UTC, lavrenchuk-dev requested changes
Missing configs

2024-04-04 06:37 UTC, merged